Repo View: Consolidate "Pull" and "Selective Pull"
1. "Pull" remains visible on the toolbar
   
   Exception: There are no diffs. 

2. When clicking "Pull", it runs what was previously "Selective Pull" 

   A popup asking to confirm which objects should be pulled is shown.

   Exception: There are only new objects, for example, when doing the initial pull of a repo. In this case, no popup is shown and the objects are pulled automatically.

3. "Advanced > Selective Pull" has been removed from the toolbar

Closes #5013