Refactor: Remove `delete_tadir` flag
After an object has been deleted successfully, abapGit will drop the `TADIR` entry regardless. The flag is not necessary anymore and has been removed.

Exception: The flag remains in the bridge to stay compatible

Closes https://github.com/abapGit/abapGit/issues/5263